resources:
  - url: http://127.0.0.1:5000/ratp-card.js
    type: module
views:
  - cards:
      - type: custom:ratp-card
        name: Ratp Card Development
        entity: sun.sun
        test_gui: true
